# Generated by Django 5.1 on 2024-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_tutorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subjects',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Both', 'Both')], default='Both', max_length=50),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Both', 'Both')], default='Both', max_length=50),
        ),
    ]
