# Generated by Django 5.1 on 2024-08-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_grade_studentprofile_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
