# Generated by Django 5.1 on 2024-08-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tutorprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.CharField(blank=True, choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Both', 'Both')], max_length=255, null=True),
        ),
    ]
