# Generated by Django 5.1 on 2024-08-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_studentprofile_tutorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bookings', to='users.studentprofile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tutorprofile')),
            ],
        ),
    ]
